# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/motonary/Fortuna
    docker:
      - image: circleci/golang:1.11
    environment:
      - GOPATH: /home/circleci/go
      - GOCACHE: "/tmp/go/cache"
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
            - dep
      - run:
          name: ensure
          command: |
            if [ ! -d vendor ]; then
              if ! type dep >/dev/null 2>&1; then
                go get github.com/golang/dep/cmd/dep
              fi
              dep ensure
            fi
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: dep
          paths:
            - /go/bin/dep
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}--
            - build-cache-master--
            - build-cache-
      - save_cache:
          key: build-cache-{{ .Branch }}--{{ .Revision }}
          paths:
              - /tmp/go/cache
          when: on_fail
      - run:
          name: prepare cache dir if not exists
          command: mkdir -p $GOCACHE
      - persist_to_workspace:
          root: /
          paths:
            - tmp/go/cache
            - go/src/github.com/motonary/Fortuna/builds

  test:
    working_directory: /go/src/github.com/motonary/Fortuna
    environment:
      - GOPATH: /home/circleci/go
      - GOCACHE: "/tmp/go/cache"
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mysql:5.7.24
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --sql-mode="no_auto_create_user,no_engine_substitution"
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_DATABASE: circleci_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - attach_workspace:
          at: /
      - run: sudo apt-get install mysql-client --allow-unauthenticated
      - run:
          name: install sql-migrate
          command: go get -v github.com/rubenv/sql-migrate/...
      - run: pwd; which sql-migrate;
      - run:
          name: migration
          command: sql-migrate up -config="config/migration_config_ci.yml" -env="test"
      - run:
          name: run go test
          command: GO_ENV=test go test ./...
      - save_cache:
          key: build-cache-{{ .Branch }}--{{ .Revision }}
          paths:
              - /tmp/go/cache
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - builds

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build
