driver: mysql
development:
  user: Motonary
  pass: ririco722
  db: fortuna_dev
  protocol: ""
  option: charset=utf8&parseTime=True&loc=Local # enable time.Time

test:
  user: Motonary
  pass: ririco722
  db: fortuna_test
  protocol: ""
  option: charset=utf8&parseTime=True&loc=Local

# production:
#   user: Motonary
#   pass: passwords
#   db: fortuna_production
#   protocol: ""
#   option: charset=utf8&parseTime=True&loc=Local
