development:
  dialect: mysql
  dir: database/migrations
  datasource: Motonary:ririco722@/fortuna?parseTime=true

test:
  dialect: mysql
  dir: database/migrations
  datasource: Motonary:ririco722@/fortuna_test?parseTime=true

# production:
#   dialect: mysql
#   dir: migrations/postgres
#   datasource: dbname=myapp sslmode=disable
#   table: migrations
