development:
  dialect: mysql
  dir: database/migrations
  datasource: Motonary:ririco722@/fortuna?charset=utf8&parseTime=True&loc=Local

test:
  dialect: mysql
  dir: database/migrations
  datasource: Motonary:ririco722@/fortuna_test?charset=utf8&parseTime=True&loc=Local

# production:
#   dialect: mysql
#   dir: database/migrations
#   datasource: dbname=myapp sslmode=disable
#   table: migrations
